name: Deploy Vue Calculator

on:
  push:
    branches:
      - main # O la rama que uses para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm ci 
      working-directory: ./calculadora-vue 
    - name: Build Vue application
      run: npm run build
      working-directory: ./calculadora-vue 

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v4.1.0 
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "calculadora-vue/dist/" 
        TARGET: "/var/www/html/calculator-app" 