name: Deploy Vue Calculator

on:
  push:
    branches:
      - main # O la rama que uses para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Puedes ajustar la versión de Node.js según sea necesario

    - name: Install dependencies
      run: npm ci # o npm install
      working-directory: ./calculadora-vue # Asegúrate de que este sea el directorio de tu aplicación Vue

    - name: Build Vue application
      run: npm run build
      working-directory: ./calculadora-vue # Asegúrate de que este sea el directorio de tu aplicación Vue

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v4.1.0 # Usa una acción de despliegue SSH
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "calculadora-vue/dist/" # Ruta de la carpeta 'dist' generada por Vue
        TARGET: "/var/www/html/calculator-app" # Directorio de destino en tu servidor (ajusta según tu configuración)
        # Puedes añadir más opciones si es necesario, como borrar el contenido anterior
        # ARGS: "-avz --delete"